In [1]:
# import numpy library
import numpy as np

In [2]:
# create two square matrix
X = np.array([[1,5,6],[8,5,9],[1,0,3]])
Z = np.array([[12,20,-3],[5,-8,5],[6,9,17]])

In [3]:
print(X,'\n')
print(Z)

[[1 5 6]
 [8 5 9]
 [1 0 3]] 

[[12 20 -3]
 [ 5 -8  5]
 [ 6  9 17]]


In [4]:
# Add and subtract the matrices X and Z
r_added = X.__add__(Z)
Z_subtracted_from_X = X.__sub__(Z)
print(r_added,'\n')
print(Z_subtracted_from_X)

[[13 25  3]
 [13 -3 14]
 [ 7  9 20]] 

[[-11 -15   9]
 [  3  13   4]
 [ -5  -9 -14]]


In [5]:
# piecewise multiplication and multiplication of two matrices
r_piecewise = X.__mul__(Z)
r_mul = X.__matmul__(Z)
print(r_piecewise,'\n')
print(r_mul)

[[ 12 100 -18]
 [ 40 -40  45]
 [  6   0  51]] 

[[ 73  34 124]
 [175 201 154]
 [ 30  47  48]]


In [6]:
# create the matrix for chemist's problem
A = np.array([[1,1],[10,35]])
b = np.array([[2],[30]])

In [7]:
# verify the size of matrix A and size of vector b
print('dim. of matrix A = ',A.shape)
print('dim. of vector b = ',b.shape)

dim. of matrix A =  (2, 2)
dim. of vector b =  (2, 1)


In [8]:
# the det(A) !=0?
np.linalg.det(A)

25.000000000000007

In [9]:
# let's find the solution
inv_A = np.linalg.inv(A)
print(inv_A)

[[ 1.4  -0.04]
 [-0.4   0.04]]


In [14]:
# finding the results
x = inv_A.dot(b)
print('The solution is',x)

The solution is [[1.6]
 [0.4]]


In [16]:
# define the matrix B
B = np.array([[1,2,6],[1,-1,4],[2,1,5]])
b = np.array([[8],[5],[13]])
print('Matrix B =\n',B)
print('vector b =\n',b)


Matrix B =
 [[ 1  2  6]
 [ 1 -1  4]
 [ 2  1  5]]
vector b =
 [[ 8]
 [ 5]
 [13]]


In [17]:
# computing the det. of B
print(np.linalg.det(B))

14.999999999999993


In [18]:
# find the inverse
inv_B = np.linalg.inv(B)

In [20]:
X = inv_B.dot(b)
print('Solution is ', X)

Solution is  [[6.]
 [1.]
 [0.]]


In [21]:
# checking your results
x1 = 6
x2 = 1
x3 = 0
if (x1+2*x2+6*x3==8):
    print('The equation 1 was satisfied')
else:
    print('The equation 1 was not satisfied')

The equation 1 was satisfied
